In [2]:
import os
import pandas as pd

In [3]:
os.chdir(r"C:\Users\snehi\Downloads\EDA")

In [4]:
os.listdir()

['Airbnb_Bookings.csv',
 'Airbnb_Hosts.csv',
 'Airbnb_Images.csv',
 'Airbnb_Listings.csv']

In [5]:
dataset={}
for file in os.listdir():
    if file.endswith(".csv"):
        df=pd.read_csv(file)
        dataset[file.replace(".csv","")]=df
print(dataset.keys())

dict_keys(['Airbnb_Bookings', 'Airbnb_Hosts', 'Airbnb_Images', 'Airbnb_Listings'])

In [6]:
dataset["Airbnb_Bookings"].head()

,Listing_Id,Booking_Id,Booking_Date,Check_In_Date,Check_Out_Date,Booking_Status
0,1,3000,2024-02-16,2024-03-13,2024-03-17,Cancelled
1,2,3001,2024-01-08,2024-01-17,2024-01-22,Confirmed
2,2,3002,2024-03-04,2024-03-19,2024-03-22,Confirmed
3,2,3003,2024-12-10,2025-01-03,2025-01-09,Cancelled
4,2,3004,2024-05-14,2024-06-02,2024-06-06,Cancelled

In [7]:
dataset["Airbnb_Bookings"].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1013 entries, 0 to 1012
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Listing_Id      1013 non-null   int64
 1   Booking_Id      1013 non-null   int64
 2   Booking_Date    1013 non-null   object
 3   Check_In_Date   1013 non-null   object
 4   Check_Out_Date  1013 non-null   object
 5   Booking_Status  1013 non-null   object
dtypes: int64(2), object(4)
memory usage: 47.6+ KB

In [8]:
bookings = dataset["Airbnb_Bookings"]

bookings[["Booking_Date","Check_In_Date","Check_Out_Date"]] = bookings[
    ["Booking_Date","Check_In_Date","Check_Out_Date"]
].apply(pd.to_datetime)

In [9]:
bookings.columns=bookings.columns.str.strip()

In [10]:
bookings.isnull().sum()

Listing_Id        0
Booking_Id        0
Booking_Date      0
Check_In_Date     0
Check_Out_Date    0
Booking_Status    0
dtype: int64

In [11]:
bookings.duplicated().sum()

np.int64(0)

In [12]:
bookings = bookings[
    (bookings["Check_In_Date"] > bookings["Booking_Date"]) &
    (bookings["Check_Out_Date"] > bookings["Check_In_Date"])
]

In [13]:
bookings["Booking_Status"].nunique()

2

In [14]:
bookings["Booking_Status"] = bookings["Booking_Status"].str.title()

In [15]:
bookings.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1013 entries, 0 to 1012
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Listing_Id      1013 non-null   int64
 1   Booking_Id      1013 non-null   int64
 2   Booking_Date    1013 non-null   datetime64[ns]
 3   Check_In_Date   1013 non-null   datetime64[ns]
 4   Check_Out_Date  1013 non-null   datetime64[ns]
 5   Booking_Status  1013 non-null   object
dtypes: datetime64[ns](3), int64(2), object(1)
memory usage: 47.6+ KB

In [16]:
bb=dataset["Airbnb_Hosts"]
bb.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Host_Id     500 non-null    int64
 1   Listing_Id  500 non-null    int64
 2   Host_Type   500 non-null    object
dtypes: int64(2), object(1)
memory usage: 11.8+ KB

In [17]:
bb.head()

   Host_Id  Listing_Id     Host_Type
0     1001           1  Professional
1     1002           2      New Host
2     1003           3  Professional
3     1004           4      New Host
4     1005           5  Professional

In [18]:
bb.isnull().sum()

Host_Id       0
Listing_Id    0
Host_Type     0
dtype: int64

In [19]:
bb.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
495    False
496    False
497    False
498    False
499    False
Length: 500, dtype: bool

In [20]:
bb.columns=bb.columns.str.strip()

In [21]:
bb["Host_Type"].nunique()

3

In [22]:

bookings.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1013 entries, 0 to 1012
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Listing_Id      1013 non-null   int64
 1   Booking_Id      1013 non-null   int64
 2   Booking_Date    1013 non-null   datetime64[ns]
 3   Check_In_Date   1013 non-null   datetime64[ns]
 4   Check_Out_Date  1013 non-null   datetime64[ns]
 5   Booking_Status  1013 non-null   object
dtypes: datetime64[ns](3), int64(2), object(1)
memory usage: 47.6+ KB

In [23]:
Images=dataset["Airbnb_Images"]
Images.head()

   Listing_Id  Image_Id  Image_Count  Image_Quality_Score
0           1      2001           13                 3.04
1           2      2002            3                 3.86
2           3      2003            4                 4.68
3           4      2004           13                 3.78
4           5      2005           12                 3.36

In [24]:
Images.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 4 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Listing_Id           500 non-null    int64
 1   Image_Id             500 non-null    int64
 2   Image_Count          500 non-null    int64
 3   Image_Quality_Score  500 non-null    float64
dtypes: float64(1), int64(3)
memory usage: 15.8 KB

In [25]:
Images.isnull().sum()

Listing_Id             0
Image_Id               0
Image_Count            0
Image_Quality_Score    0
dtype: int64

In [26]:
Images.duplicated().sum()

np.int64(0)

In [27]:
Images.columns=Images.columns.str.strip()

In [28]:
Images.describe()

       Listing_Id     Image_Id  Image_Count  Image_Quality_Score
count  500.000000   500.000000   500.000000           500.000000
mean   250.500000  2250.500000     7.646000             4.002600
std    144.481833   144.481833     4.052348             0.553672
min      1.000000  2001.000000     1.000000             3.000000
25%    125.750000  2125.750000     4.000000             3.510000
50%    250.500000  2250.500000     8.000000             4.040000
75%    375.250000  2375.250000    11.000000             4.460000
max    500.000000  2500.000000    14.000000             4.990000

In [29]:
Images.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 4 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Listing_Id           500 non-null    int64
 1   Image_Id             500 non-null    int64
 2   Image_Count          500 non-null    int64
 3   Image_Quality_Score  500 non-null    float64
dtypes: float64(1), int64(3)
memory usage: 15.8 KB

In [30]:
Listings=dataset["Airbnb_Listings"]
Listings.head()

   Listing_Id Posting_Date Posting_Time Location
0           1   2023-11-24         8:11  Houston
1           2   2023-02-27        18:16    Miami
2           3   2023-01-13         1:06  Chicago
3           4   2023-05-21        19:27    Miami
4           5   2023-05-06        11:46    Miami

In [31]:
Listings.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Listing_Id    500 non-null    int64
 1   Posting_Date  500 non-null    object
 2   Posting_Time  500 non-null    object
 3   Location      500 non-null    object
dtypes: int64(1), object(3)
memory usage: 15.8+ KB

In [32]:
Listings[["Posting_Date","Posting_Time"]]=Listings[["Posting_Date","Posting_Time"]].apply(pd.to_datetime)

C:\Users\snehi\AppData\Local\Temp\ipykernel_15536\31927407.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  Listings[["Posting_Date","Posting_Time"]]=Listings[["Posting_Date","Posting_Time"]].apply(pd.to_datetime)

In [33]:
Listings.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Listing_Id    500 non-null    int64
 1   Posting_Date  500 non-null    datetime64[ns]
 2   Posting_Time  500 non-null    datetime64[ns]
 3   Location      500 non-null    object
dtypes: datetime64[ns](2), int64(1), object(1)
memory usage: 15.8+ KB

In [34]:
Listings.head()

   Listing_Id Posting_Date        Posting_Time Location
0           1   2023-11-24 2026-03-09 08:11:00  Houston
1           2   2023-02-27 2026-03-09 18:16:00    Miami
2           3   2023-01-13 2026-03-09 01:06:00  Chicago
3           4   2023-05-21 2026-03-09 19:27:00    Miami
4           5   2023-05-06 2026-03-09 11:46:00    Miami

In [35]:
df['Posting_Time'] = pd.to_datetime(df['Posting_Time']).dt.time

In [36]:
Listings.head()

   Listing_Id Posting_Date Posting_Time Location
0           1   2023-11-24     08:11:00  Houston
1           2   2023-02-27     18:16:00    Miami
2           3   2023-01-13     01:06:00  Chicago
3           4   2023-05-21     19:27:00    Miami
4           5   2023-05-06     11:46:00    Miami

In [37]:
Listings.isnull().sum()

Listing_Id      0
Posting_Date    0
Posting_Time    0
Location        0
dtype: int64

In [38]:
Listings.duplicated().sum()

np.int64(0)

In [39]:
Listings.columns=Listings.columns.str.strip()

In [40]:
!pip install pyodbc
from sqlalchemy import create_engine,text

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pyodbc in c:\programdata\anaconda3\lib\site-packages (5.3.0)

In [41]:
server = '(localdb)\MSSQLLocalDB'             # or 'localhost\SQLEXPRESS'
database = 'AirBnb'
driver = 'ODBC Driver 18 for SQL Server'  # replace with your installed driver

# Create SQLAlchemy engine with Windows Authentication
connection_string = f'mssql+pyodbc://@{server}/{database}?driver={driver.replace(" ", "+")}&trusted_connection=yes'
engine = create_engine(connection_string)

try:
    with engine.connect() as conn:
        result = conn.execute(text("SELECT 1"))
        print("Connection successful:", result.fetchone())
except Exception as e:
    print("Connection failed:", e)

for table_name, df in dataset.items():
    try:
        print(f"Inserting {table_name}...")
        df.to_sql(
            name=table_name,
            con=engine,
            if_exists='replace',
            index=False
        )
        print(f"✅ {table_name} inserted successfully\n")
        
    except Exception as e:
        print(f"❌ Error inserting {table_name}")
        print(e)
        print("\n-----------------\n")

Connection successful: (1,)
Inserting Airbnb_Bookings...
✅ Airbnb_Bookings inserted successfully

Inserting Airbnb_Hosts...
✅ Airbnb_Hosts inserted successfully

Inserting Airbnb_Images...
✅ Airbnb_Images inserted successfully

Inserting Airbnb_Listings...
✅ Airbnb_Listings inserted successfully